grpc:
  server:
    port: 9090  # ??????? ???? ???? ??? GRPC-???????
    netty-server:
      reuse-address: true
    security:
      enabled: false # Отключить TLS
spring:
  main:
    web-application-type: none  # ?????????? Web-??????? Tomcat
  profiles:
    active: default



